### ISSUE TITLE
ECS.8 Search for card in sequence editor

### ISSUE THREAD

**Issue by ashkjones** [PonderTeam/ponder-app#36]
## User Story 
As a user I want a search bar, to easily find and select the card I want in a sequence

## Sub-tasks 
- [x] Search bar in the card lists
- [x] Filter function
- [x] As the user type in the search bar, cards are updated to match the search

## Notes
- depends on #31 
- Look into using array.includes(substring) to filter cards
- I would do this before you do #35

**Comment by ashkjones** [comment]
To modify the style of the search bar input, you can add this code
```scss
  #searchbar:focus {
    outline: thin solid mat.get-theme-color($theme, on-surface-variant);
  }
```
inside the theme function in the _sequence-editor-theme.scss file at https://github.com/PonderTeam/ponder-app/blob/9825f291bf21ee5bf87586571918f30f206dc135/src/app/sequence-editor/_sequence-editor-theme.scss

Modify the 
- first parameter "thin" to change the width
- second parameter to change line style (ex. solid, dotted, dashed)
- third parameter for the color

We want to keep an outline on focus for accessibility

**Comment by euilee0129** [comment]
for the search bar, it boldens the amount that I want, but still boldens the border on-click, but do we mind that, or should we have it so that there is no border that boldens at all when clicked?
